# Generated by Django 5.0.1 on 2024-01-20 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonsapp', '0005_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='ссылка_видео'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='lessonsapp.course', verbose_name='курс'),
        ),
    ]
