# Generated by Django 5.0.1 on 2024-01-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonsapp', '0006_alter_lesson_video_alter_subscription_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='описание'),
        ),
    ]
