# Generated by Django 5.0.1 on 2024-01-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonsapp', '0007_alter_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.CharField(blank=True, default=100, null=True, verbose_name='price'),
        ),
    ]
