# Generated by Django 5.0.1 on 2024-01-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonsapp', '0008_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.CharField(blank=True, default=100, null=True, verbose_name='стоимость_урока'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(blank=True, default=100, null=True, verbose_name='стоимость_курса'),
        ),
    ]
